#!/usr/bin/env node

const fs = require('fs');
const path = require('path');

const ROOT_DIR = path.join(__dirname, '..');
const MODEL_GAMEMODEL_DIR = path.join(ROOT_DIR, 'model', 'gameModel');

/**
 * Identify an object carrying a "visibility" field so it can be matched against
 * the equivalent object in another gamemodel.json export. "name" identifies a
 * variable descriptor, "contentKey" a library (GameModelContent), "code" a
 * language. These are the only fields stable across different exports of the
 * same gameModel: refId is re-generated by Wegas on every export.
 */
function identifyDescriptor(obj) {
  const key = obj.name ?? obj.contentKey ?? obj.code;
  return key == null ? null : `${obj['@class'] || ''}::${key}`;
}

/**
 * Recursively walk a parsed JSON value, collecting the visibility of every
 * object `identify` can put a name to.
 */
function collectVisibilities(value, identify, out = new Map()) {
  if (Array.isArray(value)) {
    for (const item of value) collectVisibilities(item, identify, out);
  } else if (value && typeof value === 'object') {
    if ('visibility' in value) {
      const id = identify(value);
      if (id != null) out.set(id, value.visibility);
    }
    for (const child of Object.values(value)) collectVisibilities(child, identify, out);
  }
  return out;
}

/**
 * Recursively walk a parsed JSON value, overwriting the visibility of every
 * object `identify` can put a name to with the value from `visibilities`,
 * when it differs. Mutates `value` in place and returns how many it touched.
 */
function applyVisibilities(value, identify, visibilities) {
  let patched = 0;

  if (Array.isArray(value)) {
    for (const item of value) patched += applyVisibilities(item, identify, visibilities);
  } else if (value && typeof value === 'object') {
    if ('visibility' in value) {
      const id = identify(value);
      if (id != null && visibilities.has(id) && visibilities.get(id) !== value.visibility) {
        value.visibility = visibilities.get(id);
        patched++;
      }
    }
    for (const child of Object.values(value)) patched += applyVisibilities(child, identify, visibilities);
  }

  return patched;
}

function writeJson(filePath, data) {
  fs.writeFileSync(filePath, JSON.stringify(data, null, 2) + '\n', 'utf-8');
}

/**
 * Patch every object with a visibility field in <targetDir>/gamemodel.json
 * (variable descriptors, libraries, languages, ...) to match the equivalent
 * object in model/gameModel/gamemodel.json.
 */
function patchGameModel(targetDir, verbose) {
  const modelFile = path.join(MODEL_GAMEMODEL_DIR, 'gamemodel.json');
  const targetFile = path.join(targetDir, 'gamemodel.json');

  if (!fs.existsSync(targetFile)) {
    if (verbose) console.log(`No gamemodel.json in ${targetDir}, skipping`);
    return 0;
  }

  const model = JSON.parse(fs.readFileSync(modelFile, 'utf-8'));
  const target = JSON.parse(fs.readFileSync(targetFile, 'utf-8'));

  const modelVisibilities = collectVisibilities(model, identifyDescriptor);
  const patched = applyVisibilities(target, identifyDescriptor, modelVisibilities);

  writeJson(targetFile, target);
  if (verbose) console.log(`Patched ${patched} object(s) in ${path.relative(ROOT_DIR, targetFile)}`);
  return patched;
}

/**
 * Patch the visibility of every entry in <targetDir>/filesmeta.json to match
 * the entry for the same file path in model/gameModel/filesmeta.json.
 */
function patchFilesMeta(targetDir, verbose) {
  const modelFile = path.join(MODEL_GAMEMODEL_DIR, 'filesmeta.json');
  const targetFile = path.join(targetDir, 'filesmeta.json');

  if (!fs.existsSync(targetFile)) {
    if (verbose) console.log(`No filesmeta.json in ${targetDir}, skipping`);
    return 0;
  }

  const model = JSON.parse(fs.readFileSync(modelFile, 'utf-8'));
  const target = JSON.parse(fs.readFileSync(targetFile, 'utf-8'));

  let patched = 0;
  for (const [filePath, meta] of Object.entries(target)) {
    const modelMeta = model[filePath];
    if (
      modelMeta &&
      meta &&
      typeof meta === 'object' &&
      'visibility' in meta &&
      modelMeta.visibility !== meta.visibility
    ) {
      meta.visibility = modelMeta.visibility;
      patched++;
    }
  }

  writeJson(targetFile, target);
  if (verbose) console.log(`Patched ${patched} entry(ies) in ${path.relative(ROOT_DIR, targetFile)}`);
  return patched;
}

function main() {
  const args = process.argv.slice(2);
  const verbose = args.includes('--verbose') || args.includes('-v');
  const targetDir = args.find(arg => !arg.startsWith('-'));

  if (!targetDir) {
    console.error('Usage: node patchVisibility.js <path/to/gameModel> [--verbose]');
    process.exit(1);
  }

  if (!fs.existsSync(path.join(MODEL_GAMEMODEL_DIR, 'gamemodel.json'))) {
    console.error(`Cannot find ${path.relative(ROOT_DIR, MODEL_GAMEMODEL_DIR)}/gamemodel.json`);
    process.exit(1);
  }

  if (!fs.existsSync(targetDir)) {
    console.error(`${targetDir} does not exist`);
    process.exit(1);
  }

  const gameModelPatched = patchGameModel(targetDir, verbose);
  const filesMetaPatched = patchFilesMeta(targetDir, verbose);

  console.log(
    `Visibility patched: ${gameModelPatched} gamemodel.json object(s), ${filesMetaPatched} filesmeta.json entry(ies)`
  );
}

main();
