export enum ActionType {
  'ACTION' = 'ACTION',
  'CASU_RADIO' = 'CASU_RADIO',
  'ACTORS_RADIO' = 'ACTORS_RADIO',
  'RESOURCES_RADIO' = 'RESOURCES_RADIO',
  'EVASAN_RADIO' = 'EVASAN_RADIO',
  'ALLOCATE_RESOURCES' = 'ALLOCATE_RESOURCES',
}
