export enum ActionType {
  ACTION = 'ACTION',
  CASU_RADIO = 'CASU_RADIO',
  ACTORS_RADIO = 'ACTORS_RADIO',
  RESOURCES_RADIO = 'RESOURCES_RADIO',
  EVASAN_RADIO = 'EVASAN_RADIO',
  ALLOCATE_RESOURCES = 'ALLOCATE_RESOURCES',
  PRETRIAGE_REPORT = 'PRETRIAGE_REPORT',
}

export type RadioType =
  | ActionType.CASU_RADIO
  | ActionType.ACTORS_RADIO
  | ActionType.RESOURCES_RADIO
  | ActionType.EVASAN_RADIO;
